# Generated by Django 4.1.4 on 2022-12-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='adresse',
            new_name='address',
        ),
    ]
